openapi: 3.0.0
info:
  title: Calculadora API
  version: 1.0.0
  description: API RESTful para operações matemáticas básicas.
paths:
  /calculations/sum:
    post:
      summary: Soma um vetor de inteiros
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numbers:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
        '400':
          description: Erro (ex.: vetor inválido)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /calculations/average:
    post:
      summary: Calcula a média aritmética de um vetor de inteiros
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numbers:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
        '400':
          description: Erro (ex.: vetor inválido)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string